# Generated by Django 2.1.5 on 2019-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='otp_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
