# Generated by Django 2.1.5 on 2019-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='entity',
            new_name='cart_rubbish',
        ),
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='long',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubbish',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
