# Generated by Django 2.1.5 on 2019-03-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190209_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
