# Generated by Django 2.1.5 on 2019-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='opt',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default=23, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
