# Generated by Django 2.1.5 on 2019-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190310_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
