# Generated by Django 2.1.5 on 2019-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190310_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(1, 'BASIC'), (2, 'AGENT'), (3, 'BUSINESS')], default=1),
        ),
    ]
