# Generated by Django 2.1.5 on 2019-03-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
